import "./globals.css";
import type { Metadata } from "next";
import { Martian_Mono } from "next/font/google";
import Footer from "./components/layout/Footer";
import Nav from "./components/layout/Nav";

const martian = Martian_Mono({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${martian.className} bg-stone-900`}>
        <Nav />
        {children}
        <Footer />
      </body>
    </html>
  );
}
